# Copyright (c) 2025 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0

# Reusable workflow to perform operator version update
# To perform csm-operator version update, needs three arguments as input to the workflow
name: Module version update

on:
  workflow_call:
    inputs:
      csm-version:
        description: 'CSM program version, ex: v1.12.0, v1.13.0, ...'
        required: true
        type: string
      update-option:
        description: 'Select the update flag, ex. "nightly" or "tag"'
        required: true
        type: string
 
jobs:
  read-values:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout csm repository
      uses: actions/checkout@v2
      with:
        repository: dell/csm
        path: csm

    - name: Read values from csm-versions.yaml
      id: read_values
      run: |
        pwd
        csm_version=$(grep -E '^csm-version' csm/config/csm-versions.yaml | cut -d ':' -f 2 | tr -d ' ')
        csm_operator=$(grep -E '^csm-operator' csm/config/csm-versions.yaml | cut -d ':' -f 2 | tr -d ' ')
        csi_powerscale=$(grep -E '^csi-powerscale' csm/config/csm-versions.yaml | cut -d ':' -f 2 | tr -d ' ')
        csi_powerstore=$(grep -E '^csi-powerstore' csm/config/csm-versions.yaml | cut -d ':' -f 2 | tr -d ' ')
        csi_powermax=$(grep -E '^csi-powermax' csm/config/csm-versions.yaml | cut -d ':' -f 2 | tr -d ' ')
        csi_vxflexos=$(grep -E '^csi-vxflexos' csm/config/csm-versions.yaml | cut -d ':' -f 2 | tr -d ' ')
        csi_unity=$(grep -E '^csi-unity' csm/config/csm-versions.yaml | cut -d ':' -f 2 | tr -d ' ')
        csm_replication=$(grep -E '^csm-replication' csm/config/csm-versions.yaml | cut -d ':' -f 2 | tr -d ' ')
        karavi_resiliency=$(grep -E '^karavi-resiliency' csm/config/csm-versions.yaml | cut -d ':' -f 2 | tr -d ' ')
        csm_authorization_v2=$(grep -E '^csm-authorization-v2' csm/config/csm-versions.yaml | cut -d ':' -f 2 | tr -d ' ')
        csireverseproxy=$(grep -E '^csireverseproxy' csm/config/csm-versions.yaml | cut -d ':' -f 2 | tr -d ' ')
        karavi_observability=$(grep -E '^karavi-observability' csm/config/csm-versions.yaml | cut -d ':' -f 2 | tr -d ' ')
        karavi_metrics_powerflex=$(grep -E '^karavi-metrics-powerflex' csm/config/csm-versions.yaml | cut -d ':' -f 2 | tr -d ' ')
        csm_metrics_powerstore=$(grep -E '^csm-metrics-powerstore' csm/config/csm-versions.yaml | cut -d ':' -f 2 | tr -d ' ')
        csm_metrics_powerscale=$(grep -E '^csm-metrics-powerscale' csm/config/csm-versions.yaml | cut -d ':' -f 2 | tr -d ' ')
        csm_metrics_powermax=$(grep -E '^csm-metrics-powermax' csm/config/csm-versions.yaml | cut -d ':' -f 2 | tr -d ' ')
        karavi_topology=$(grep -E '^karavi-topology' csm/config/csm-versions.yaml | cut -d ':' -f 2 | tr -d ' ')
        otel_collector=$(grep -E '^otel-collector' csm/config/csm-versions.yaml | cut -d ':' -f 2 | tr -d ' ')
        
        echo "CSM_VERSION=$csm_version" >> $GITHUB_ENV
        echo "CSM_OPERATOR=$csm_operator" >> $GITHUB_ENV
        echo "CSI_POWERSCALE=$csi_powerscale" >> $GITHUB_ENV
        echo "CSI_POWERSTORE=$csi_powerstore" >> $GITHUB_ENV
        echo "CSI_POWERMAX=$csi_powermax" >> $GITHUB_ENV
        echo "CSI_VXFLEXOS=$csi_vxflexos" >> $GITHUB_ENV
        echo "CSI_UNITY=$csi_unity" >> $GITHUB_ENV
        echo "CSM_REPLICATION=$csm_replication" >> $GITHUB_ENV
        echo "KARAVI_RESILIENCY=$karavi_resiliency" >> $GITHUB_ENV
        echo "CSM_AUTHORIZATION_V2=$csm_authorization_v2" >> $GITHUB_ENV
        echo "CSIREVERSEPROXY=$csireverseproxy" >> $GITHUB_ENV
        echo "KARAVI_OBSERVABILITY=$karavi_observability" >> $GITHUB_ENV
        echo "KARAVI_METRICS_POWERFLEX=$karavi_metrics_powerflex" >> $GITHUB_ENV
        echo "CSM_METRICS_POWERSTORE=$csm_metrics_powerstore" >> $GITHUB_ENV
        echo "CSM_METRICS_POWERSCALE=$csm_metrics_powerscale" >> $GITHUB_ENV
        echo "CSM_METRICS_POWERMAX=$csm_metrics_powermax" >> $GITHUB_ENV
        echo "KARAVI_TOPOLOGY=$karavi_topology" >> $GITHUB_ENV
        echo "OTEL_COLLECTOR=$otel_collector" >> $GITHUB_ENV

    - name: Checkout csm-operator repository
      uses: actions/checkout@v2
      with:
        repository: nitesh3108/csm-operator

    - name: Print environment variables
      run: |
          echo "Version provided --> ${{ inputs.csm-version }}"
          input_ver=${{ inputs.csm-version }}
          echo "Version from csm repo --> $CSM_VERSION"
          echo "Flag provided --> ${{ inputs.update-option}}"
         
          if [ "$CSM_VERSION" == "${{ inputs.csm-version }}" ]; then
          echo " Versions are maching"
          else
          echo "Make sure the Latest version is updated to csm repo csm-version.yaml file"
          fi

          trim_csm_version=${CSM_VERSION//./}
          trim_input_version=${input_ver//./}

          echo "csm ver --> $trim_csm_version"
          echo "input ver --> $trim_input_version"

          if [ "$trim_csm_version" == "$trim_input_version" ]; then
          echo " Versions are maching"
          else
          echo "Make sure the Latest version is updated to csm repo csm-version.yaml file"
          fi

          w_csm_versio=$(echo $CSM_VERSION | sed 's/v//')
          w_input_version=$(echo $input_ver | sed 's/v//')

          if [ "${w_input_version}" == "${w_csm_versio}" ]; then 
          echo " Versions are maching"
          else
          echo "Make sure the Latest version is updated to csm repo csm-version.yaml file"
          fi

          if [[ "$w_input_version" == "${w_csm_versio}" ]]; then 
          echo " Versions are maching"
          else
          echo "Make sure the Latest version is updated to csm repo csm-version.yaml file"
          fi

          echo "NEWWW"
          if [ "$w_csm_versio -eq "$w_input_version" ]; then
          echo "NEWW, matching"
          else
          echo "NEWW, not matching"
          fi
      shell: bash
